project_name: watch-tower

builds:
  - id: watch-tower
    main: ./cmd/watch-tower
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.FullCommit}} -X main.date={{.Date}}

archives:
  - id: archive
    builds: [watch-tower]
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

sboms:
  - artifacts: archive

release:
  mode: replace
  header: |
    ## {{ .Tag }}
    
    {{ .ReleaseNotes }}
  
  footer: |
    ## Installation
    
    Download the binary for your platform from the assets below, or install via Go:
    
    ```bash
    go install github.com/devblac/watch-tower/cmd/watch-tower@{{ .Tag }}
    ```
    
    See the [README](https://github.com/devblac/watch-tower#quick-start) for usage instructions.


